; ============================================================
;  RFID-FORGE — univerzalni RFID cti/pis/klonuj nastroj
;  Deska: NodeMCU ESP-32S
; ============================================================

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; LittleFS drzi soubor data/index.html (webova stranka)
board_build.filesystem = littlefs

lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    bblanchon/ArduinoJson @ ^7.1.0
    ESP32Async/AsyncTCP @ ^3.3.2
    ESP32Async/ESPAsyncWebServer @ ^3.7.0
